# Generated by Django 3.1.3 on 2020-11-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Paciente',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('apellido', models.CharField(max_length=50, verbose_name='nombre del paciente')),
    #             ('nombre', models.CharField(max_length=50, verbose_name='apellido del paciente')),
    #         ],
    #     ),
    # ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50, verbose_name='nombre del paciente')),
                ('nombre', models.CharField(max_length=50, verbose_name='apellido del paciente')),
                ('dni', models.CharField(default='0', max_length=10, verbose_name='dni del paciente')),
                # ('activo', models.BooleanField(default=True)),
            ],
       ),
    ]