# Generated by Django 3.1.3 on 2020-11-25 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipopago', models.IntegerField(choices=[(1, 'efectivo'), (3, 'cheque'), (2, 'tarjeta')], default=1)),
                ('estado', models.IntegerField(choices=[(1, 'pendiente'), (2, 'taller'), (3, 'nose')], default=1)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pedidopacientes', to='pacientes.paciente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pedidovendedores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
