# Generated by Django 3.1.3 on 2020-11-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipopago',
            field=models.IntegerField(choices=[(1, 'efectivo'), (2, 'tarjeta'), (3, 'cheque')], default=1),
        ),
    ]
