# Generated by Django 3.1.3 on 2020-11-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('pedidos', '0003_auto_20201125_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(2, 'taller2'), (1, 'pendiente1'), (3, 'nose3')], default=1),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.FloatField(default=0)),
                ('opcion', models.CharField(max_length=500)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productodeitem', to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidodeitem', to='pedidos.pedido')),
            ],
        ),
    ]
