# Generated by Django 3.1.3 on 2020-11-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
