# Generated by Django 3.1.3 on 2020-11-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_atendido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'get_latest_by': ['-fecha']},
        ),
    ]
