# Generated by Django 3.1.3 on 2020-11-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20201118_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'get_latest_by': ['fecha']},
        ),
    ]
