# Generated by Django 3.1.3 on 2020-11-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_auto_20201118_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['-atendido']},
        ),
    ]
