# Generated by Django 3.1.3 on 2020-11-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_auto_20201118_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', '-hora', '-atendido']},
        ),
    ]
