# Generated by Django 3.1.3 on 2020-11-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_auto_20201118_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'hora']},
        ),
    ]
