# Generated by Django 3.1.3 on 2020-11-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_activo'),
        ('turnos', '0012_auto_20201119_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='turnopacientes', to='pacientes.paciente'),
        ),
    ]
