# Generated by Django 3.1.3 on 2020-11-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialobservacion',
            old_name='fechahora',
            new_name='fecha',
        ),
    ]
